### In this notebook I will:
pull data from detentions the year 2025 for NY

In [3]:
## import necessary libraries
import pandas as pd

In [4]:
from datetime import datetime

In [18]:
df1 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/Detentions/2026-ICLI-00005_Detentions_FY25_20260311_Redacted.xlsx')
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICE Detentions FY2023 - FY2026YTD (10/01/2022 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890985,2025-09-30 16:52:00,2025-09-30 16:52:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:52:00,2025-09-30 16:52:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890986,2025-09-30 16:56:00,2025-09-30 16:56:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:57:00,2025-09-30 16:57:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890987,2025-09-30 16:58:00,2025-09-30 16:58:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:58:00,2025-09-30 16:58:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890988,2025-09-30 16:59:00,2025-09-30 16:59:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:59:00,2025-09-30 16:59:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890989,2025-08-06 15:30:00,2025-08-06 15:30:00,MONTGOMERY PROCESSING CTR,2025-08-24 09:08:00,2025-08-24 09:08:00,Removed,2025-08-24 00:00:00,Removed,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Montgomery County, TX Sub Office",Houston Area of Responsibility,NaN

In [19]:
df1 = df1.iloc[5:]
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
6,2024-12-27 01:16:00,2024-12-27 01:16:00,FLORENCE STAGING FACILITY,2024-12-27 08:48:00,2024-12-27 08:48:00,Removed,2024-12-27 00:00:00,Removed,NaN,Male,...,2024-11-13 00:00:00,Border Patrol,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,00001bc128707c1bc0f44bfd6fcc3fa9c3d4f195
7,2025-09-17 10:00:00,2025-09-17 10:00:00,DALLAS F.O. HOLD,2025-09-18 19:02:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE",Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
8,2025-09-17 10:00:00,2025-09-18 22:43:00,BLUEBONNET DET FCLTY,2025-09-26 09:28:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Bluebonnet Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
9,2025-09-17 10:00:00,2025-09-26 17:25:00,PRAIRIELAND DETENTION CENTER,2025-09-27 12:03:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Prairieland Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890985,2025-09-30 16:52:00,2025-09-30 16:52:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:52:00,2025-09-30 16:52:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890986,2025-09-30 16:56:00,2025-09-30 16:56:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:57:00,2025-09-30 16:57:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890987,2025-09-30 16:58:00,2025-09-30 16:58:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:58:00,2025-09-30 16:58:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890988,2025-09-30 16:59:00,2025-09-30 16:59:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:59:00,2025-09-30 16:59:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890989,2025-08-06 15:30:00,2025-08-06 15:30:00,MONTGOMERY PROCESSING CTR,2025-08-24 09:08:00,2025-08-24 09:08:00,Removed,2025-08-24 00:00:00,Removed,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Montgomery County, TX Sub Office",Houston Area of Responsibility,NaN

In [20]:
df1.columns = df1.iloc[0]
df1_titled = df1[1:].reset_index(drop=True)
df1_titled

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
0,2024-12-27 01:16:00,2024-12-27 01:16:00,FLORENCE STAGING FACILITY,2024-12-27 08:48:00,2024-12-27 08:48:00,Removed,2024-12-27 00:00:00,Removed,NaN,Male,...,2024-11-13 00:00:00,Border Patrol,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,00001bc128707c1bc0f44bfd6fcc3fa9c3d4f195
1,2025-09-17 10:00:00,2025-09-17 10:00:00,DALLAS F.O. HOLD,2025-09-18 19:02:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE",Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
2,2025-09-17 10:00:00,2025-09-18 22:43:00,BLUEBONNET DET FCLTY,2025-09-26 09:28:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Bluebonnet Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
3,2025-09-17 10:00:00,2025-09-26 17:25:00,PRAIRIELAND DETENTION CENTER,2025-09-27 12:03:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Prairieland Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-09-27 12:04:00,PINE PRAIRIE ICE PROCESSING CENTER,2025-10-02 15:20:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890979,2025-09-30 16:52:00,2025-09-30 16:52:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:52:00,2025-09-30 16:52:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890980,2025-09-30 16:56:00,2025-09-30 16:56:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:57:00,2025-09-30 16:57:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890981,2025-09-30 16:58:00,2025-09-30 16:58:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:58:00,2025-09-30 16:58:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890982,2025-09-30 16:59:00,2025-09-30 16:59:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:59:00,2025-09-30 16:59:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890983,2025-08-06 15:30:00,2025-08-06 15:30:00,MONTGOMERY PROCESSING CTR,2025-08-24 09:08:00,2025-08-24 09:08:00,Removed,2025-08-24 00:00:00,Removed,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Montgomery County, TX Sub Office",Houston Area of Responsibility,NaN

In [21]:
df1_titled['Stay Book In Date Time'] = pd.to_datetime(df1_titled['Stay Book In Date Time'])

In [22]:
dfDetentions1 = df1_titled.loc[
  (df1_titled["Stay Book In Date Time"] >= "2025-01-01") &
  (df1_titled["Stay Book In Date Time"] <= "2025-12-31")
]

In [23]:
dfDetentions1

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
1,2025-09-17 10:00:00,2025-09-17 10:00:00,DALLAS F.O. HOLD,2025-09-18 19:02:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE",Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
2,2025-09-17 10:00:00,2025-09-18 22:43:00,BLUEBONNET DET FCLTY,2025-09-26 09:28:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Bluebonnet Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
3,2025-09-17 10:00:00,2025-09-26 17:25:00,PRAIRIELAND DETENTION CENTER,2025-09-27 12:03:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Prairieland Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-09-27 12:04:00,PINE PRAIRIE ICE PROCESSING CENTER,2025-10-02 15:20:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
5,2025-07-15 12:50:00,2025-07-15 12:50:00,INDIANAPOLIS HOLD ROOM,2025-07-15 15:00:00,2025-07-25 06:08:00,Transferred,2025-07-25 00:00:00,Removed,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Indianapolis, IN Sub-Office",Chicago Area of Responsibility,0000518998357378d65efc37aee9a476ad110db1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890979,2025-09-30 16:52:00,2025-09-30 16:52:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:52:00,2025-09-30 16:52:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890980,2025-09-30 16:56:00,2025-09-30 16:56:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:57:00,2025-09-30 16:57:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890981,2025-09-30 16:58:00,2025-09-30 16:58:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:58:00,2025-09-30 16:58:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890982,2025-09-30 16:59:00,2025-09-30 16:59:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:59:00,2025-09-30 16:59:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890983,2025-08-06 15:30:00,2025-08-06 15:30:00,MONTGOMERY PROCESSING CTR,2025-08-24 09:08:00,2025-08-24 09:08:00,Removed,2025-08-24 00:00:00,Removed,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Montgomery County, TX Sub Office",Houston Area of Responsibility,NaN

In [24]:
dfDetentions1.to_csv('FilteredData/2025ICEDetentions1.csv', index=False)

In [25]:
df2 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/Detentions/2026-ICLI-00005_Detentions_FY26_20260311_Redacted.xlsx')
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICE Detentions FY2023 - FY2026YTD (10/01/2022 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628147,2026-03-10 18:05:00,2026-03-10 18:05:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:07:00,2026-03-10 18:07:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628148,2026-03-10 18:10:00,2026-03-10 18:10:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:10:00,2026-03-10 18:10:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628149,2026-03-10 16:10:00,2026-03-10 16:10:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,2026-02-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN
628150,2026-03-10 18:38:00,2026-03-10 18:38:00,ATLANTA DIST. HOLD RM,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE",Atlanta Area of Responsibility,NaN
628151,2026-03-10 20:35:00,2026-03-10 20:35:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN

In [26]:
df2 = df2.iloc[5:]
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
6,2025-11-16 12:58:00,2025-11-16 12:58:00,AUSTIN DRO HOLD ROOM,2025-11-16 16:27:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Austin, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
7,2025-11-16 12:58:00,2025-11-16 16:41:00,T DON HUTTO DETENTION CENTER,2025-11-25 04:16:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Hutto, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
8,2025-11-16 12:58:00,2025-11-26 22:15:00,AZ REM OP COORD CENTER (AROCC),2025-11-28 00:50:00,2025-11-28 00:50:00,Removed,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
9,2025-09-17 10:00:00,2025-10-02 15:23:00,ALEXANDRIA STAGING FACILITY,2025-10-05 11:30:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628147,2026-03-10 18:05:00,2026-03-10 18:05:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:07:00,2026-03-10 18:07:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628148,2026-03-10 18:10:00,2026-03-10 18:10:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:10:00,2026-03-10 18:10:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628149,2026-03-10 16:10:00,2026-03-10 16:10:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,2026-02-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN
628150,2026-03-10 18:38:00,2026-03-10 18:38:00,ATLANTA DIST. HOLD RM,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE",Atlanta Area of Responsibility,NaN
628151,2026-03-10 20:35:00,2026-03-10 20:35:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN

In [28]:
df2.columns = df2.iloc[0]
df2_titled = df2[1:].reset_index(drop=True)
df2_titled

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
0,2025-11-16 12:58:00,2025-11-16 12:58:00,AUSTIN DRO HOLD ROOM,2025-11-16 16:27:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Austin, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-16 12:58:00,2025-11-16 16:41:00,T DON HUTTO DETENTION CENTER,2025-11-25 04:16:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Hutto, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
2,2025-11-16 12:58:00,2025-11-26 22:15:00,AZ REM OP COORD CENTER (AROCC),2025-11-28 00:50:00,2025-11-28 00:50:00,Removed,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
3,2025-09-17 10:00:00,2025-10-02 15:23:00,ALEXANDRIA STAGING FACILITY,2025-10-05 11:30:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-10-05 11:36:00,River Correctional Center,2025-11-13 17:04:00,2025-11-13 17:04:00,Removed,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628141,2026-03-10 18:05:00,2026-03-10 18:05:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:07:00,2026-03-10 18:07:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628142,2026-03-10 18:10:00,2026-03-10 18:10:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:10:00,2026-03-10 18:10:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628143,2026-03-10 16:10:00,2026-03-10 16:10:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,2026-02-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN
628144,2026-03-10 18:38:00,2026-03-10 18:38:00,ATLANTA DIST. HOLD RM,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE",Atlanta Area of Responsibility,NaN
628145,2026-03-10 20:35:00,2026-03-10 20:35:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN

In [29]:
df2_titled['Stay Book In Date Time'] = pd.to_datetime(df2_titled['Stay Book In Date Time'])

In [31]:
dfDetentions2 = df2_titled.loc[
  (df2_titled["Stay Book In Date Time"] >= "2025-01-01") &
  (df2_titled["Stay Book In Date Time"] <= "2025-12-31")
]

In [32]:
dfDetentions2

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
0,2025-11-16 12:58:00,2025-11-16 12:58:00,AUSTIN DRO HOLD ROOM,2025-11-16 16:27:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Austin, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-16 12:58:00,2025-11-16 16:41:00,T DON HUTTO DETENTION CENTER,2025-11-25 04:16:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Hutto, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
2,2025-11-16 12:58:00,2025-11-26 22:15:00,AZ REM OP COORD CENTER (AROCC),2025-11-28 00:50:00,2025-11-28 00:50:00,Removed,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
3,2025-09-17 10:00:00,2025-10-02 15:23:00,ALEXANDRIA STAGING FACILITY,2025-10-05 11:30:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-10-05 11:36:00,River Correctional Center,2025-11-13 17:04:00,2025-11-13 17:04:00,Removed,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627208,2025-12-30 17:24:00,2025-12-30 17:24:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-30 17:24:00,2025-12-30 17:24:00,Voluntary Return,2025-12-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627209,2025-12-30 17:28:00,2025-12-30 17:28:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-30 17:29:00,2025-12-30 17:29:00,Voluntary Return,2025-12-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627210,2025-12-30 17:29:00,2025-12-30 17:29:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-30 17:29:00,2025-12-30 17:29:00,Voluntary Return,2025-12-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627211,2025-12-30 17:32:00,2025-12-30 17:32:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-30 17:32:00,2025-12-30 17:32:00,Voluntary Return,2025-12-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627212,2025-12-30 17:36:00,2025-12-30 17:36:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-30 17:37:00,2025-12-30 17:37:00,Voluntary Return,2025-12-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN

In [33]:
dfDetentions2.to_csv('FilteredData/2025ICEDetentions2.csv', index=False)

In [34]:
pdList = [dfDetentions1, dfDetentions2]
df_Detentions2025 = pd.concat(pdList).drop_duplicates()
df_Detentions2025

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
1,2025-09-17 10:00:00,2025-09-17 10:00:00,DALLAS F.O. HOLD,2025-09-18 19:02:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE",Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
2,2025-09-17 10:00:00,2025-09-18 22:43:00,BLUEBONNET DET FCLTY,2025-09-26 09:28:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Bluebonnet Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
3,2025-09-17 10:00:00,2025-09-26 17:25:00,PRAIRIELAND DETENTION CENTER,2025-09-27 12:03:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Prairieland Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-09-27 12:04:00,PINE PRAIRIE ICE PROCESSING CENTER,2025-10-02 15:20:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
5,2025-07-15 12:50:00,2025-07-15 12:50:00,INDIANAPOLIS HOLD ROOM,2025-07-15 15:00:00,2025-07-25 06:08:00,Transferred,2025-07-25 00:00:00,Removed,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Indianapolis, IN Sub-Office",Chicago Area of Responsibility,0000518998357378d65efc37aee9a476ad110db1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627208,2025-12-30 17:24:00,2025-12-30 17:24:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-30 17:24:00,2025-12-30 17:24:00,Voluntary Return,2025-12-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627209,2025-12-30 17:28:00,2025-12-30 17:28:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-30 17:29:00,2025-12-30 17:29:00,Voluntary Return,2025-12-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627210,2025-12-30 17:29:00,2025-12-30 17:29:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-30 17:29:00,2025-12-30 17:29:00,Voluntary Return,2025-12-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627211,2025-12-30 17:32:00,2025-12-30 17:32:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-30 17:32:00,2025-12-30 17:32:00,Voluntary Return,2025-12-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627212,2025-12-30 17:36:00,2025-12-30 17:36:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-30 17:37:00,2025-12-30 17:37:00,Voluntary Return,2025-12-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN

In [35]:
df_Detentions2025.to_csv('FilteredData/All2025ICEDetentions.csv', index=False)