### In this notebook I will:
pull data from arrests the year 2025 for NY

#### Arrests pull

In [44]:
## import necessary libraries
import pandas as pd

In [45]:
from datetime import datetime

In [46]:
df1 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/Arrests/2026-ICLI-00005_Arrests_FY25_20260311_Redacted.xlsx')
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 - 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Administrative Arrests FY2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235144,2025-09-30 16:58:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-09-30 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",ICE ERO HQ authorized operation,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
235145,2025-09-30 19:52:05,Targeted,TEXAS,NaN,Houston Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"MTG GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Montgomery County, TX Sub Office",NaN,NaN,NaN
235146,2025-09-30 20:09:40,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235147,2025-09-30 20:32:00,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235148,2025-08-19 12:38:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN

In [47]:
df1 = df1.iloc[5:]
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
6,2025-09-17 11:34:21,Targeted,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,6-Deported/Removed - Deportability,...,COLOMBIA,Male,2025-11-13 00:00:00,2022-05-18 00:00:00,DALLAS COUNTY GENERAL AREA,DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"DALLAS, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000215186a4071ae5bc250f63e6baa60b286c30
7,2025-07-15 12:35:19,NaN,INDIANA,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,HONDURAS,Male,2025-07-25 00:00:00,2025-07-15 00:00:00,"MARION COUNTY SHERIFF'S OFFICE, INDIANAPOLIS, ...",NaN,"ERO - Indianapolis, IN Sub-Office",2 Pending Criminal Charges,NaN,0000518998357378d65efc37aee9a476ad110db1
8,2025-09-19 15:18:01,Targeted,PENNSYLVANIA,NaN,Philadelphia Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Deported/Removed,...,GUATEMALA,Male,2025-09-24 00:00:00,2019-02-10 00:00:00,"PHI GENERAL AREA, NON-SPECIFIC",NaN,"PHILADELPHIA, PA, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000071be2f67e88489f0c0f0c281ff6f9cda4dda
9,2025-01-26 14:49:00,NaN,NORTH CAROLINA,NaN,Atlanta Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,GUATEMALA,Male,2025-05-27 00:00:00,NaN,"MECKLENBURG COUNTY, NC",-,"ERO - Charlotte, NC Sub-Office",3 Other Immigration Violator,NaN,0000b5b7a22827fe95d32ba770cc8ae9cc669fa9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235144,2025-09-30 16:58:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-09-30 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",ICE ERO HQ authorized operation,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
235145,2025-09-30 19:52:05,Targeted,TEXAS,NaN,Houston Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"MTG GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Montgomery County, TX Sub Office",NaN,NaN,NaN
235146,2025-09-30 20:09:40,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235147,2025-09-30 20:32:00,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235148,2025-08-19 12:38:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN

In [48]:
df1.columns = df1.iloc[0]
df1_titled = df1[1:].reset_index(drop=True)
df1_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-09-17 11:34:21,Targeted,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,6-Deported/Removed - Deportability,...,COLOMBIA,Male,2025-11-13 00:00:00,2022-05-18 00:00:00,DALLAS COUNTY GENERAL AREA,DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"DALLAS, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000215186a4071ae5bc250f63e6baa60b286c30
1,2025-07-15 12:35:19,NaN,INDIANA,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,HONDURAS,Male,2025-07-25 00:00:00,2025-07-15 00:00:00,"MARION COUNTY SHERIFF'S OFFICE, INDIANAPOLIS, ...",NaN,"ERO - Indianapolis, IN Sub-Office",2 Pending Criminal Charges,NaN,0000518998357378d65efc37aee9a476ad110db1
2,2025-09-19 15:18:01,Targeted,PENNSYLVANIA,NaN,Philadelphia Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Deported/Removed,...,GUATEMALA,Male,2025-09-24 00:00:00,2019-02-10 00:00:00,"PHI GENERAL AREA, NON-SPECIFIC",NaN,"PHILADELPHIA, PA, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000071be2f67e88489f0c0f0c281ff6f9cda4dda
3,2025-01-26 14:49:00,NaN,NORTH CAROLINA,NaN,Atlanta Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,GUATEMALA,Male,2025-05-27 00:00:00,NaN,"MECKLENBURG COUNTY, NC",-,"ERO - Charlotte, NC Sub-Office",3 Other Immigration Violator,NaN,0000b5b7a22827fe95d32ba770cc8ae9cc669fa9
4,2025-02-19 00:00:00,NaN,KANSAS,NaN,Chicago Area of Responsibility,Detained Docket Control,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-04-04 00:00:00,2020-02-07 00:00:00,"WIC GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Wichita, KS Sub-Office",2 Pending Criminal Charges,NaN,00019569acea0c5120fc0e55d6254c7d4aad2b22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235138,2025-09-30 16:58:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-09-30 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",ICE ERO HQ authorized operation,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
235139,2025-09-30 19:52:05,Targeted,TEXAS,NaN,Houston Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"MTG GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Montgomery County, TX Sub Office",NaN,NaN,NaN
235140,2025-09-30 20:09:40,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235141,2025-09-30 20:32:00,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235142,2025-08-19 12:38:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN

In [49]:
df1_titled['Apprehension Date'] = pd.to_datetime(df1_titled['Apprehension Date'])

In [50]:
df1_titled.info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235143 entries, 0 to 235142
Data columns (total 25 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Apprehension Date           235143 non-null  datetime64[ns]
 1   Apprehension Type           56922 non-null   object
 2   State                       209509 non-null  object
 3   County                      0 non-null       object
 4   TOA Current Duty AOR        233440 non-null  object
 5   Apprehension Final Program  235143 non-null  object
 6   Arresting Agency            235143 non-null  object
 7   Apprehension Method         235143 non-null  object
 8   Apprehension Criminality    235143 non-null  object
 9   Case Status                 230257 non-null  object
 10  Case Category               230257 non-null  object
 11  Departure Country           188534 non-null  object
 12  Final Order Yes No          230257 non-null  object
 13  Birth Date                  235142 non-null  object
 14  Birth Year                  235142 non-null  object
 15  Citizenship Country         235143 non-null  object
 16  Gender                      235143 non-null  object
 17  Departed Date               188570 non-null  object
 18  Final Order Date            160401 non-null  object
 19  Apprehension Site Landmark  233250 non-null  object
 20  Operation                   39807 non-null   object
 21  TOA Current Duty Site       235143 non-null  object
 22  Case Criminality            230257 non-null  object
 23  Case Threat Level           94718 non-null   object
 24  Anonymized Identifier       231785 non-null  object
dtypes: datetime64[ns](1), object(24)
memory usage: 44.9+ MB

In [52]:
##disregard, Apprehension AOR is no longer there

In [ ]:
print(dfArrests0['Fruit'].nunique())

In [32]:
#This gets arrests with New York area of responsibility and/or the state of NY
co_arrests = arrests[
    (arrests['Apprehension AOR'] == 'Denver Area of Responsibility') |
    (arrests['Apprehension State'] == 'Colorado') | (arrests['Apprehension State'] == 'Wyoming')
]
co_arrests.info()

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
14,2025-09-16 08:33:41,Collateral,NEW YORK,NaN,Boston Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,BRAZIL,Male,2025-12-22 00:00:00,2025-12-04 00:00:00,FUGITIVE OPERATIONS MA,Boston,"BOSTON, MA, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,0003d477c82b5f0795916635f4da101d37d6924c
43,2025-01-28 12:26:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,SENEGAL,Male,2025-04-10 00:00:00,2023-03-03 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000c16c2e97d9a2d6a84ec0954b1fd204ee96634
52,2025-07-25 11:29:25,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-10-23 00:00:00,2025-09-26 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000e1b3e91ccc931e58311ebe59363dfb727adc9
70,2025-06-09 13:03:41,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0014a87083eb6ebdd1e1d6563016150e7aa8ae50
99,2025-09-12 14:29:15,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,ECUADOR,Male,2025-12-02 00:00:00,2019-10-28 00:00:00,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",1 Convicted Criminal,3,001c20aa9fa402e9dfe2fe2552a49ce677540953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232928,2025-06-18 14:47:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Other efforts,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
233100,2025-06-25 21:57:38,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Other efforts,3 Other Immigration Violator,NaN,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
233101,2025-06-25 22:57:16,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
234948,2025-09-22 15:07:00,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,Child Exploitation & Sex Tourism,"ERO - Champlain, NY Sub-Office",NaN,NaN,NaN
235142,2025-08-19 12:38:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN

In [34]:
dfArrests1.to_csv('FilteredData/2025ICEArrests1.csv', index=False)

In [35]:
df2 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/Arrests/2026-ICLI-00005_Arrests_FY26_20260311_Redacted.xlsx')
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 - 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Administrative Arrests FY2026YTD (10/01/20...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191547,2026-03-10 17:07:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191548,2026-03-10 17:22:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191549,2026-03-10 17:21:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191550,2026-03-10 16:14:39,Collateral,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,RAINS COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN
191551,2026-03-10 18:26:43,NaN,NaN,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,NaN,...,COLOMBIA,Female,NaN,NaN,NaN,NaN,"CHICAGO-O'HARE INTERNATIONAL AIRPORT, CHICAGO ...",NaN,NaN,NaN

In [36]:
df2 = df2.iloc[5:]
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
6,2025-11-16 14:21:59,Targeted,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-11-28 00:00:00,2024-08-01 00:00:00,FRU - ALL AREAS INISDE BEXAR COUNTY,-,"ERO - Austin, TX Sub Office",3 Other Immigration Violator,NaN,0000004d7b875782a3b6f2b460f98c0750a5a899
7,2025-11-05 14:29:30,Collateral,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Female,2025-12-02 00:00:00,2025-10-28 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,3,0000d8cb192bc69cea76779ab037c4a6d98f176e
8,2025-12-14 08:18:33,Targeted,UTAH,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-20 00:00:00,2025-12-15 00:00:00,"SLC GENERAL AREA, NON-SPECIFIC",-,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE",1 Convicted Criminal,2,000123c8701799c3f1c69fc5b9237441afcf6161
9,2026-02-14 10:27:08,Targeted,FLORIDA,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,287(g) Program,2 Pending Criminal Charges,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"FMY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Fort Myers, FL Sub Office",2 Pending Criminal Charges,NaN,0001c9598ba1c9866270b617f4c82ff2e04d3e29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191547,2026-03-10 17:07:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191548,2026-03-10 17:22:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191549,2026-03-10 17:21:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191550,2026-03-10 16:14:39,Collateral,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,RAINS COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN
191551,2026-03-10 18:26:43,NaN,NaN,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,NaN,...,COLOMBIA,Female,NaN,NaN,NaN,NaN,"CHICAGO-O'HARE INTERNATIONAL AIRPORT, CHICAGO ...",NaN,NaN,NaN

In [37]:
df2.columns = df2.iloc[0]
df2_titled = df2[1:].reset_index(drop=True)
df2_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-11-16 14:21:59,Targeted,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-11-28 00:00:00,2024-08-01 00:00:00,FRU - ALL AREAS INISDE BEXAR COUNTY,-,"ERO - Austin, TX Sub Office",3 Other Immigration Violator,NaN,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-05 14:29:30,Collateral,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Female,2025-12-02 00:00:00,2025-10-28 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,3,0000d8cb192bc69cea76779ab037c4a6d98f176e
2,2025-12-14 08:18:33,Targeted,UTAH,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-20 00:00:00,2025-12-15 00:00:00,"SLC GENERAL AREA, NON-SPECIFIC",-,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE",1 Convicted Criminal,2,000123c8701799c3f1c69fc5b9237441afcf6161
3,2026-02-14 10:27:08,Targeted,FLORIDA,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,287(g) Program,2 Pending Criminal Charges,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"FMY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Fort Myers, FL Sub Office",2 Pending Criminal Charges,NaN,0001c9598ba1c9866270b617f4c82ff2e04d3e29
4,2025-11-19 07:44:46,Targeted,ILLINOIS,NaN,Chicago Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2026-01-28 00:00:00,2026-01-22 00:00:00,CHIFUGITIVE OPERATIONS,-,"CHICAGO, IL, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,000236c508a3b3fd90b47464c6790ebd2ced3228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191541,2026-03-10 17:07:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191542,2026-03-10 17:22:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191543,2026-03-10 17:21:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191544,2026-03-10 16:14:39,Collateral,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,RAINS COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN
191545,2026-03-10 18:26:43,NaN,NaN,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,NaN,...,COLOMBIA,Female,NaN,NaN,NaN,NaN,"CHICAGO-O'HARE INTERNATIONAL AIRPORT, CHICAGO ...",NaN,NaN,NaN

In [38]:
df2_titled['Apprehension Date'] = pd.to_datetime(df2_titled['Apprehension Date'])

In [39]:
dfArrests2 = df2_titled.loc[
  (df2_titled["Apprehension Date"] >= "2025-01-01") &
  (df2_titled["Apprehension Date"] <= "2025-12-31") &
  (df2_titled["State"] == "NEW YORK")
]

In [40]:
dfArrests2

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
150,2025-11-11 07:00:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,MEXICO,Male,2025-11-16 00:00:00,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0039dff0156f320292971c05a14bfa6e3946cb32
167,2025-12-17 09:30:47,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Female,2026-01-27 00:00:00,2026-01-06 00:00:00,ERIE COUNTY,NaN,"BUFFALO, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00415c1cb95bdf48f01e661ab7a9f918d36407be
228,2025-11-03 09:00:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-24 00:00:00,2025-12-04 00:00:00,"NBG GENERAL AREA, NON-SPECIFIC",-,"Newburgh NY, Sub-Office",1 Convicted Criminal,2,0054d4ce81786b739538665b21b90a7e3a369dac
260,2025-11-17 12:40:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,EL SALVADOR,Male,2026-02-06 00:00:00,2026-01-28 00:00:00,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",2 Pending Criminal Charges,NaN,005ca75a7a1899aec34184d6f6c85fdf988ac97a
271,2025-12-05 09:59:03,Collateral,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,00611d42a3c81d54bb49e55b9d6e1593de0ddf67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184814,2025-10-21 08:34:15,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,EL SALVADOR,Male,NaN,NaN,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN
185156,2025-10-31 07:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
186543,2025-12-03 10:26:19,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,GUATEMALA,Male,NaN,NaN,"NBG GENERAL AREA, NON-SPECIFIC",NaN,"Newburgh NY, Sub-Office",NaN,NaN,NaN
186642,2025-12-04 17:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
189191,2025-12-28 20:40:32,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,ECUADOR,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [41]:
dfArrests2.to_csv('FilteredData/2025ICEArrests2.csv', index=False)

In [42]:
pdList = [dfArrests1, dfArrests2]
df_Arrests2025 = pd.concat(pdList).drop_duplicates()
df_Arrests2025

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
14,2025-09-16 08:33:41,Collateral,NEW YORK,NaN,Boston Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,BRAZIL,Male,2025-12-22 00:00:00,2025-12-04 00:00:00,FUGITIVE OPERATIONS MA,Boston,"BOSTON, MA, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,0003d477c82b5f0795916635f4da101d37d6924c
43,2025-01-28 12:26:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,SENEGAL,Male,2025-04-10 00:00:00,2023-03-03 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000c16c2e97d9a2d6a84ec0954b1fd204ee96634
52,2025-07-25 11:29:25,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-10-23 00:00:00,2025-09-26 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000e1b3e91ccc931e58311ebe59363dfb727adc9
70,2025-06-09 13:03:41,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0014a87083eb6ebdd1e1d6563016150e7aa8ae50
99,2025-09-12 14:29:15,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,ECUADOR,Male,2025-12-02 00:00:00,2019-10-28 00:00:00,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",1 Convicted Criminal,3,001c20aa9fa402e9dfe2fe2552a49ce677540953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184814,2025-10-21 08:34:15,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,EL SALVADOR,Male,NaN,NaN,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN
185156,2025-10-31 07:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
186543,2025-12-03 10:26:19,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,GUATEMALA,Male,NaN,NaN,"NBG GENERAL AREA, NON-SPECIFIC",NaN,"Newburgh NY, Sub-Office",NaN,NaN,NaN
186642,2025-12-04 17:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
189191,2025-12-28 20:40:32,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,ECUADOR,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [43]:
df_Arrests2025.to_csv('FilteredData/All2025ICEArrests.csv', index=False)