### In this notebook I will:
pull data from Removals the year 2025

In [1]:
## import necessary libraries
import pandas as pd

In [2]:
from datetime import datetime

In [16]:
df1 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/Removals/2026-ICLI-00005_Removals_FY25_20260311_Redacted.xlsx')
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICE Removals FY2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367408,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2025-09-30 16:51:17,NO,NaN,I6A,212a6Ai,YES,NaN
367409,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Detained Docket Control,ICE,2025-09-30 16:54:16,NO,NaN,I6A,212a6Ai,NO,NaN
367410,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2025-09-30 16:55:52,NO,NaN,I6A,212a6Ai,NO,NaN
367411,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Detained Docket Control,ICE,2025-09-30 16:58:11,NO,NaN,I6A,212a6Ai,NO,NaN
367412,2024-12-23 00:00:00,"HIDALGO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,[9] VR Under Safeguards,ERO Criminal Alien Program,ICE,2026-01-08 08:17:27,NO,NaN,I6A,212a6Ai,NO,NaN

In [17]:
df1 = df1.iloc[5:]
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
5,Departed Date,Port of Departure,Departure Country,Case AOR,State,County,Case Status,Gender,Birth Country,Citizenship Country,...,TOA Case Category,Latest Apprehension Final Program,Latest Arresting Agency,Latest Apprehension Date,Final Order Yes No,Final Order Date,Final Charge Code,Final Charge Section,Prior Deport Yes No,Anonymized Identifier
6,2024-12-27 00:00:00,"NOGALES, AZ, POE",MEXICO,Phoenix Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Male,MEXICO,MEXICO,...,NaN,Border Patrol,CBP,2024-11-27 07:27:21,YES,2024-11-27 00:00:00,I9C2,212a9CiII,YES,00001bc128707c1bc0f44bfd6fcc3fa9c3d4f195
7,2025-07-25 00:00:00,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",HONDURAS,Chicago Area of Responsibility,INDIANA,NaN,8-Excluded/Removed - Inadmissibility,Male,HONDURAS,HONDURAS,...,[8F] Expedited Removal,ERO Criminal Alien Program,ICE,2025-07-15 12:35:19,YES,2025-07-15 00:00:00,I7A1,212a7AiI,NO,0000518998357378d65efc37aee9a476ad110db1
8,2025-09-24 00:00:00,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,HQ Area of Responsibility,NaN,NaN,8-Excluded/Deported/Removed,Male,GUATEMALA,GUATEMALA,...,NaN,Non-Detained Docket Control,ICE,2025-09-19 15:18:01,YES,2019-02-10 00:00:00,I9C2,212a9CiII,YES,000071be2f67e88489f0c0f0c281ff6f9cda4dda
9,2024-12-07 00:00:00,"LOS ANGELES, CA, POE",EL SALVADOR,Los Angeles Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Female,EL SALVADOR,EL SALVADOR,...,NaN,Border Patrol,CBP,2024-03-12 02:24:16,NO,NaN,I6A,212a6Ai,NO,000074d1ba231a7ed7631619097aa7a834ad5bbf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367408,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2025-09-30 16:51:17,NO,NaN,I6A,212a6Ai,YES,NaN
367409,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Detained Docket Control,ICE,2025-09-30 16:54:16,NO,NaN,I6A,212a6Ai,NO,NaN
367410,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2025-09-30 16:55:52,NO,NaN,I6A,212a6Ai,NO,NaN
367411,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Detained Docket Control,ICE,2025-09-30 16:58:11,NO,NaN,I6A,212a6Ai,NO,NaN
367412,2024-12-23 00:00:00,"HIDALGO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,[9] VR Under Safeguards,ERO Criminal Alien Program,ICE,2026-01-08 08:17:27,NO,NaN,I6A,212a6Ai,NO,NaN

In [18]:
df1.columns = df1.iloc[0]
df1_titled = df1[1:].reset_index(drop=True)
df1_titled

5,Departed Date,Port of Departure,Departure Country,Case AOR,State,County,Case Status,Gender,Birth Country,Citizenship Country,...,TOA Case Category,Latest Apprehension Final Program,Latest Arresting Agency,Latest Apprehension Date,Final Order Yes No,Final Order Date,Final Charge Code,Final Charge Section,Prior Deport Yes No,Anonymized Identifier
0,2024-12-27 00:00:00,"NOGALES, AZ, POE",MEXICO,Phoenix Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Male,MEXICO,MEXICO,...,NaN,Border Patrol,CBP,2024-11-27 07:27:21,YES,2024-11-27 00:00:00,I9C2,212a9CiII,YES,00001bc128707c1bc0f44bfd6fcc3fa9c3d4f195
1,2025-07-25 00:00:00,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",HONDURAS,Chicago Area of Responsibility,INDIANA,NaN,8-Excluded/Removed - Inadmissibility,Male,HONDURAS,HONDURAS,...,[8F] Expedited Removal,ERO Criminal Alien Program,ICE,2025-07-15 12:35:19,YES,2025-07-15 00:00:00,I7A1,212a7AiI,NO,0000518998357378d65efc37aee9a476ad110db1
2,2025-09-24 00:00:00,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,HQ Area of Responsibility,NaN,NaN,8-Excluded/Deported/Removed,Male,GUATEMALA,GUATEMALA,...,NaN,Non-Detained Docket Control,ICE,2025-09-19 15:18:01,YES,2019-02-10 00:00:00,I9C2,212a9CiII,YES,000071be2f67e88489f0c0f0c281ff6f9cda4dda
3,2024-12-07 00:00:00,"LOS ANGELES, CA, POE",EL SALVADOR,Los Angeles Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Female,EL SALVADOR,EL SALVADOR,...,NaN,Border Patrol,CBP,2024-03-12 02:24:16,NO,NaN,I6A,212a6Ai,NO,000074d1ba231a7ed7631619097aa7a834ad5bbf
4,2025-07-05 00:00:00,"ORLANDO, FL, POE",PERU,San Antonio Area of Responsibility,TEXAS,NaN,8-Excluded/Removed - Inadmissibility,Male,PERU,PERU,...,NaN,Non-Detained Docket Control,ICE,2024-02-02 09:54:00,YES,2025-05-23 00:00:00,I6A,212a6Ai,NO,0000aec67e823c9306515cc63f285a76fc3b6591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367402,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2025-09-30 16:51:17,NO,NaN,I6A,212a6Ai,YES,NaN
367403,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Detained Docket Control,ICE,2025-09-30 16:54:16,NO,NaN,I6A,212a6Ai,NO,NaN
367404,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2025-09-30 16:55:52,NO,NaN,I6A,212a6Ai,NO,NaN
367405,2025-09-30 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Detained Docket Control,ICE,2025-09-30 16:58:11,NO,NaN,I6A,212a6Ai,NO,NaN
367406,2024-12-23 00:00:00,"HIDALGO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,[9] VR Under Safeguards,ERO Criminal Alien Program,ICE,2026-01-08 08:17:27,NO,NaN,I6A,212a6Ai,NO,NaN

In [13]:
df1_titled['Departed Date'] = pd.to_datetime(df1_titled['Departed Date'])

In [14]:
dfRemovals1 = df1_titled.loc[
  (df1_titled["Departed Date"] >= "2025-01-01") &
  (df1_titled["Departed Date"] <= "2025-12-31")
]

In [15]:
dfRemovals1

Empty DataFrame
Columns: [Departed Date, Port of Departure, Departure Country, Case AOR, State, County, Case Status, Gender, Birth Country, Citizenship Country, Birth Date, Birth Year, Entry Date, Entry Status, Known Terrorist Yes No, Suspected Gang Yes No, MSC Charge, MSC Charge Date, MSC Criminal Charge Status, MSC Charge Code, MSC Conviction Date, Case Criminality, Case Threat Level, Aggravated Felon Yes No, Processing Disposition, Case Category, Final Program, Final Program Code, Arresting Agency, TOA Case Category, Latest Apprehension Final Program, Latest Arresting Agency, Latest Apprehension Date, Final Order Yes No, Final Order Date, Final Charge Code, Final Charge Section, Prior Deport Yes No, Anonymized Identifier]
Index: []

[0 rows x 39 columns]

In [34]:
dfArrests1.to_csv('FilteredData/2025ICEArrests1.csv', index=False)

In [25]:
df2 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/Removals/2026-ICLI-00005_Removals_FY26_20260311_Redacted.xlsx')
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICE Removals FY2026 (10/01/2025 - 03/10/2026),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191269,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 16:52:27,NO,NaN,I6A,212a6Ai,NO,NaN
191270,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 17:06:52,NO,NaN,I6A,212a6Ai,NO,NaN
191271,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Fugitive Operations,ICE,2026-03-10 17:07:39,NO,NaN,I6A,212a6Ai,NO,NaN
191272,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 17:22:39,NO,NaN,I6A,212a6Ai,YES,NaN
191273,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 17:21:11,NO,NaN,I6A,212a6Ai,NO,NaN

In [26]:
df2 = df2.iloc[5:]
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
5,Departed Date,Port of Departure,Departure Country,Case AOR,State,County,Case Status,Gender,Birth Country,Citizenship Country,...,TOA Case Category,Latest Apprehension Final Program,Latest Arresting Agency,Latest Apprehension Date,Final Order Yes No,Final Order Date,Final Charge Code,Final Charge Section,Prior Deport Yes No,Anonymized Identifier
6,2025-11-28 00:00:00,"PHOENIX, AZ, POE",VENEZUELA,San Antonio Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Male,VENEZUELA,VENEZUELA,...,[8E] Inadmissible - ICE Fugitive,ERO Criminal Alien Program,ICE,2025-11-16 14:21:59,YES,2024-08-01 00:00:00,I6A,212a6Ai,NO,0000004d7b875782a3b6f2b460f98c0750a5a899
7,2025-11-13 00:00:00,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",COLOMBIA,Dallas Area of Responsibility,NaN,NaN,6-Deported/Removed - Deportability,Male,COLOMBIA,COLOMBIA,...,NaN,Fugitive Operations,ICE,2025-09-17 11:34:21,YES,2022-05-18 00:00:00,R1B,237a1B,NO,0000215186a4071ae5bc250f63e6baa60b286c30
8,2025-12-10 00:00:00,"LOS ANGELES, CA, AIRPORT, POE",TURKIYE,Los Angeles Area of Responsibility,NaN,NaN,8-Excluded/Deported/Removed,Male,TURKIYE,TURKIYE,...,NaN,Border Patrol,CBP,2022-09-16 17:37:19,YES,2026-02-06 00:00:00,I7A1,212a7AiI,NO,0000c7d9da9c69c9608dea3bed45f38250f60e31
9,2025-12-02 00:00:00,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",COLOMBIA,San Antonio Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Female,COLOMBIA,COLOMBIA,...,NaN,ERO Criminal Alien Program,ICE,2025-11-05 14:29:30,YES,2025-10-28 00:00:00,I7A1,212a7AiI,NO,0000d8cb192bc69cea76779ab037c4a6d98f176e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191269,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 16:52:27,NO,NaN,I6A,212a6Ai,NO,NaN
191270,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 17:06:52,NO,NaN,I6A,212a6Ai,NO,NaN
191271,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Fugitive Operations,ICE,2026-03-10 17:07:39,NO,NaN,I6A,212a6Ai,NO,NaN
191272,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 17:22:39,NO,NaN,I6A,212a6Ai,YES,NaN
191273,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 17:21:11,NO,NaN,I6A,212a6Ai,NO,NaN

In [27]:
df2.columns = df2.iloc[0]
df2_titled = df2[1:].reset_index(drop=True)
df2_titled

5,Departed Date,Port of Departure,Departure Country,Case AOR,State,County,Case Status,Gender,Birth Country,Citizenship Country,...,TOA Case Category,Latest Apprehension Final Program,Latest Arresting Agency,Latest Apprehension Date,Final Order Yes No,Final Order Date,Final Charge Code,Final Charge Section,Prior Deport Yes No,Anonymized Identifier
0,2025-11-28 00:00:00,"PHOENIX, AZ, POE",VENEZUELA,San Antonio Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Male,VENEZUELA,VENEZUELA,...,[8E] Inadmissible - ICE Fugitive,ERO Criminal Alien Program,ICE,2025-11-16 14:21:59,YES,2024-08-01 00:00:00,I6A,212a6Ai,NO,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-13 00:00:00,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",COLOMBIA,Dallas Area of Responsibility,NaN,NaN,6-Deported/Removed - Deportability,Male,COLOMBIA,COLOMBIA,...,NaN,Fugitive Operations,ICE,2025-09-17 11:34:21,YES,2022-05-18 00:00:00,R1B,237a1B,NO,0000215186a4071ae5bc250f63e6baa60b286c30
2,2025-12-10 00:00:00,"LOS ANGELES, CA, AIRPORT, POE",TURKIYE,Los Angeles Area of Responsibility,NaN,NaN,8-Excluded/Deported/Removed,Male,TURKIYE,TURKIYE,...,NaN,Border Patrol,CBP,2022-09-16 17:37:19,YES,2026-02-06 00:00:00,I7A1,212a7AiI,NO,0000c7d9da9c69c9608dea3bed45f38250f60e31
3,2025-12-02 00:00:00,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",COLOMBIA,San Antonio Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Female,COLOMBIA,COLOMBIA,...,NaN,ERO Criminal Alien Program,ICE,2025-11-05 14:29:30,YES,2025-10-28 00:00:00,I7A1,212a7AiI,NO,0000d8cb192bc69cea76779ab037c4a6d98f176e
4,2025-12-20 00:00:00,"NOGALES, AZ, POE",MEXICO,Salt Lake City Area of Responsibility,UTAH,NaN,8-Excluded/Removed - Inadmissibility,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2025-12-14 08:18:33,YES,2025-12-15 00:00:00,I6A,212a6Ai,YES,000123c8701799c3f1c69fc5b9237441afcf6161
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191263,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 16:52:27,NO,NaN,I6A,212a6Ai,NO,NaN
191264,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 17:06:52,NO,NaN,I6A,212a6Ai,NO,NaN
191265,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Fugitive Operations,ICE,2026-03-10 17:07:39,NO,NaN,I6A,212a6Ai,NO,NaN
191266,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 17:22:39,NO,NaN,I6A,212a6Ai,YES,NaN
191267,2026-03-10 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2026-03-10 17:21:11,NO,NaN,I6A,212a6Ai,NO,NaN

In [30]:
df2_titled['Departed Date'] = pd.to_datetime(df2_titled['Departed Date'])

In [31]:
dfRemovals2 = df2_titled.loc[
  (df2_titled["Departed Date"] >= "2025-01-01") &
  (df2_titled["Departed Date"] <= "2025-12-31") &
  (df2_titled["State"] == "NEW YORK")
]

In [32]:
dfRemovals2

5,Departed Date,Port of Departure,Departure Country,Case AOR,State,County,Case Status,Gender,Birth Country,Citizenship Country,...,TOA Case Category,Latest Apprehension Final Program,Latest Arresting Agency,Latest Apprehension Date,Final Order Yes No,Final Order Date,Final Charge Code,Final Charge Section,Prior Deport Yes No,Anonymized Identifier
72,2025-12-02,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",ECUADOR,HQ Area of Responsibility,NEW YORK,NaN,8-Excluded/Removed - Inadmissibility,Male,ECUADOR,ECUADOR,...,NaN,Fugitive Operations,ICE,2025-09-12 14:29:15,YES,2019-10-28 00:00:00,I9A2,212a9Aii,YES,001c20aa9fa402e9dfe2fe2552a49ce677540953
156,2025-11-16,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",MEXICO,Newark Area of Responsibility,NEW YORK,NaN,3-Voluntary Departure Confirmed,Male,MEXICO,MEXICO,...,NaN,Fugitive Operations,ICE,2025-11-11 07:00:00,NO,NaN,I6A,212a6Ai,NO,0039dff0156f320292971c05a14bfa6e3946cb32
260,2025-12-09,"NEW YORK, NY (KENNEDY), POE",TAIWAN,New Orleans Area of Responsibility,NEW YORK,NaN,6-Deported/Removed - Deportability,Female,TAIWAN,TAIWAN,...,NaN,Fugitive Operations,ICE,2025-12-01 15:40:52,YES,2025-12-01 00:00:00,R1C1,237a1Ci,NO,0061d376a23ff8c9fd4cb4c4cd39374c9adde14f
262,2025-11-11,"EL PASO, TX, POE",MEXICO,El Paso Area of Responsibility,NEW YORK,NaN,3-Voluntary Departure Confirmed,Male,ECUADOR,ECUADOR,...,NaN,Fugitive Operations,ICE,2025-08-26 11:20:53,YES,2025-10-15 00:00:00,I6A,212a6Ai,NO,006262607a9c8bb4f797a62162167bd7ece6fd1b
838,2025-12-30,"MIAMI INTERNATIONAL AIRPORT, MIAMI FLORIDA, POE",DOMINICAN REPUBLIC,Phoenix Area of Responsibility,NEW YORK,NaN,3-Voluntary Departure Confirmed,Male,DOMINICAN REPUBLIC,DOMINICAN REPUBLIC,...,NaN,Homeland Security Investigations,ICE,2025-12-10 08:00:00,NO,NaN,I6A,212a6Ai,NO,0132864d5a9d3366f989e035f53d91a492e5b95a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184418,2025-11-13,"PORT ISABEL, TX, POE",ECUADOR,San Diego Area of Responsibility,NEW YORK,NaN,3-Voluntary Departure Confirmed,Male,ECUADOR,ECUADOR,...,NaN,ERO Criminal Alien Program,ICE,2025-10-01 11:50:00,NO,NaN,I6A,212a6Ai,NO,fea87025e2ef23e76aa5e800aa8f1bacb59f8b7e
184855,2025-10-07,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",EL SALVADOR,New York City Area of Responsibility,NEW YORK,NaN,3-Voluntary Departure Confirmed,Male,EL SALVADOR,EL SALVADOR,...,NaN,Non-Detained Docket Control,ICE,2025-09-11 08:55:43,NO,NaN,I6A,212a6Ai,NO,ff45ac75209245408d550e08d6b7adcd4c8f68a1
185076,2025-12-08,"PASO DEL NORTE, TX, POE",MEXICO,Philadelphia Area of Responsibility,NEW YORK,NaN,3-Voluntary Departure Confirmed,Male,MEXICO,MEXICO,...,NaN,Fugitive Operations,ICE,2025-12-03 07:50:00,NO,NaN,I6A,212a6Ai,NO,ff94921323439d6872d758e8664d025fa9c03fb1
185239,2025-12-23,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",MEXICO,New Orleans Area of Responsibility,NEW YORK,NaN,3-Voluntary Departure Confirmed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2025-09-23 12:17:32,NO,NaN,I6A,212a6Ai,NO,ffcf3d240f34287e29d5f69976eae242679dfed2
185299,2025-12-08,"PHOENIX, AZ, POE",GUATEMALA,Phoenix Area of Responsibility,NEW YORK,NaN,3-Voluntary Departure Confirmed,Male,GUATEMALA,GUATEMALA,...,NaN,Inspections - Air,CBP,2025-11-16 15:07:00,NO,NaN,I6A,212a6Ai,NO,ffe270f7b199afbf0172d42d0fb286935b9d1ccf

In [43]:
dfRemovals2.to_csv('FilteredData/All2025ICERemovals.csv', index=False)

In [34]:
df3 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/Removals/2026-ICLI-00005_Removals_FY24_20260311_Redacted.xlsx')
df3

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICE Removals FY2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343030,2024-09-27 00:00:00,"BROWNSVILLE-MATAMOR, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2024-09-27 10:59:00,NO,NaN,I6A,212a6Ai,NO,NaN
343031,2024-09-28 00:00:00,"BROWNSVILLE-MATAMOR, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2024-09-28 09:33:00,NO,NaN,I6A,212a6Ai,YES,NaN
343032,2024-09-30 00:00:00,"BROWNSVILLE, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2024-09-30 11:07:00,NO,NaN,R1B,237a1B,NO,NaN
343033,2024-07-31 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Detained Docket Control,ICE,2025-07-31 17:36:20,NO,NaN,I6A,212a6Ai,YES,NaN
343034,2023-11-29 00:00:00,"PASO DEL NORTE, TX, POE",MEXICO,El Paso Area of Responsibility,NaN,NaN,3-Voluntary Departure Confirmed,Male,MEXICO,MEXICO,...,NaN,Border Patrol,CBP,2023-11-29 17:08:24,NO,NaN,I6A,212a6Ai,NO,NaN

In [35]:
df3 = df3.iloc[5:]
df3

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
5,Departed Date,Port of Departure,Departure Country,Case AOR,State,County,Case Status,Gender,Birth Country,Citizenship Country,...,TOA Case Category,Latest Apprehension Final Program,Latest Arresting Agency,Latest Apprehension Date,Final Order Yes No,Final Order Date,Final Charge Code,Final Charge Section,Prior Deport Yes No,Anonymized Identifier
6,2024-02-03 00:00:00,"CHAMPLAIN, NY, POE",CANADA,New York City Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Male,GUINEA,GUINEA,...,NaN,Border Patrol,CBP,2024-01-27 16:56:07,YES,2025-01-16 00:00:00,I6A,212a6Ai,NO,000041f4ff0fb9afb94504de8d709abb2130d68b
7,2024-06-26 00:00:00,"SAN ANTONIO, TX, POE",HONDURAS,San Antonio Area of Responsibility,NaN,NaN,8-Excluded/Deported/Removed,Male,HONDURAS,HONDURAS,...,[16] Reinstated Final Order,ERO Criminal Alien Program,ICE,2024-06-13 08:06:00,YES,2023-12-07 00:00:00,I9A2,212a9Aii,YES,000058df2daf065f42816437ebf455e2d0d38558
8,2023-12-31 00:00:00,"LOS ANGELES, CA, POE",CANADA,Los Angeles Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Female,PERU,PERU,...,NaN,Border Patrol,CBP,2023-12-25 19:06:03,YES,2025-02-20 00:00:00,I6A,212a6Ai,NO,00006702a71893c098f76a0ba70f13f66aa3555f
9,2024-02-23 00:00:00,"MCALLEN, TX, POE",HONDURAS,Harlingen Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Female,HONDURAS,HONDURAS,...,NaN,Border Patrol,CBP,2024-02-20 04:28:15,YES,2024-02-20 00:00:00,I7A1,212a7AiI,NO,00006b9f5b12ee5ccd5628d36b0f38b1cb22dbf0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343030,2024-09-27 00:00:00,"BROWNSVILLE-MATAMOR, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2024-09-27 10:59:00,NO,NaN,I6A,212a6Ai,NO,NaN
343031,2024-09-28 00:00:00,"BROWNSVILLE-MATAMOR, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2024-09-28 09:33:00,NO,NaN,I6A,212a6Ai,YES,NaN
343032,2024-09-30 00:00:00,"BROWNSVILLE, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2024-09-30 11:07:00,NO,NaN,R1B,237a1B,NO,NaN
343033,2024-07-31 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Detained Docket Control,ICE,2025-07-31 17:36:20,NO,NaN,I6A,212a6Ai,YES,NaN
343034,2023-11-29 00:00:00,"PASO DEL NORTE, TX, POE",MEXICO,El Paso Area of Responsibility,NaN,NaN,3-Voluntary Departure Confirmed,Male,MEXICO,MEXICO,...,NaN,Border Patrol,CBP,2023-11-29 17:08:24,NO,NaN,I6A,212a6Ai,NO,NaN

In [36]:
df3.columns = df3.iloc[0]
df3_titled = df3[1:].reset_index(drop=True)
df3_titled

5,Departed Date,Port of Departure,Departure Country,Case AOR,State,County,Case Status,Gender,Birth Country,Citizenship Country,...,TOA Case Category,Latest Apprehension Final Program,Latest Arresting Agency,Latest Apprehension Date,Final Order Yes No,Final Order Date,Final Charge Code,Final Charge Section,Prior Deport Yes No,Anonymized Identifier
0,2024-02-03 00:00:00,"CHAMPLAIN, NY, POE",CANADA,New York City Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Male,GUINEA,GUINEA,...,NaN,Border Patrol,CBP,2024-01-27 16:56:07,YES,2025-01-16 00:00:00,I6A,212a6Ai,NO,000041f4ff0fb9afb94504de8d709abb2130d68b
1,2024-06-26 00:00:00,"SAN ANTONIO, TX, POE",HONDURAS,San Antonio Area of Responsibility,NaN,NaN,8-Excluded/Deported/Removed,Male,HONDURAS,HONDURAS,...,[16] Reinstated Final Order,ERO Criminal Alien Program,ICE,2024-06-13 08:06:00,YES,2023-12-07 00:00:00,I9A2,212a9Aii,YES,000058df2daf065f42816437ebf455e2d0d38558
2,2023-12-31 00:00:00,"LOS ANGELES, CA, POE",CANADA,Los Angeles Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Female,PERU,PERU,...,NaN,Border Patrol,CBP,2023-12-25 19:06:03,YES,2025-02-20 00:00:00,I6A,212a6Ai,NO,00006702a71893c098f76a0ba70f13f66aa3555f
3,2024-02-23 00:00:00,"MCALLEN, TX, POE",HONDURAS,Harlingen Area of Responsibility,NaN,NaN,8-Excluded/Removed - Inadmissibility,Female,HONDURAS,HONDURAS,...,NaN,Border Patrol,CBP,2024-02-20 04:28:15,YES,2024-02-20 00:00:00,I7A1,212a7AiI,NO,00006b9f5b12ee5ccd5628d36b0f38b1cb22dbf0
4,2024-04-25 00:00:00,"DEL RIO, TX, POE",MEXICO,San Antonio Area of Responsibility,NaN,NaN,6-Deported/Removed - Deportability,Male,MEXICO,MEXICO,...,NaN,Border Patrol,CBP,2023-10-31 15:39:50,YES,2011-06-28 00:00:00,I9A2,212a9Aii,YES,000076125b526eb027106999d067baa3309ced84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343024,2024-09-27 00:00:00,"BROWNSVILLE-MATAMOR, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2024-09-27 10:59:00,NO,NaN,I6A,212a6Ai,NO,NaN
343025,2024-09-28 00:00:00,"BROWNSVILLE-MATAMOR, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2024-09-28 09:33:00,NO,NaN,I6A,212a6Ai,YES,NaN
343026,2024-09-30 00:00:00,"BROWNSVILLE, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,ERO Criminal Alien Program,ICE,2024-09-30 11:07:00,NO,NaN,R1B,237a1B,NO,NaN
343027,2024-07-31 00:00:00,"LAREDO, TX, POE",MEXICO,Harlingen Area of Responsibility,TEXAS,NaN,9-VR Witnessed,Male,MEXICO,MEXICO,...,NaN,Detained Docket Control,ICE,2025-07-31 17:36:20,NO,NaN,I6A,212a6Ai,YES,NaN
343028,2023-11-29 00:00:00,"PASO DEL NORTE, TX, POE",MEXICO,El Paso Area of Responsibility,NaN,NaN,3-Voluntary Departure Confirmed,Male,MEXICO,MEXICO,...,NaN,Border Patrol,CBP,2023-11-29 17:08:24,NO,NaN,I6A,212a6Ai,NO,NaN

In [37]:
df3_titled['Departed Date'] = pd.to_datetime(df3_titled['Departed Date'])

In [41]:
dfRemovals3 = df3_titled.loc[
  (df3_titled["Departed Date"] >= "2025-01-01") &
  (df3_titled["Departed Date"] <= "2025-12-31")
]

In [42]:
dfRemovals3

Empty DataFrame
Columns: [Departed Date, Port of Departure, Departure Country, Case AOR, State, County, Case Status, Gender, Birth Country, Citizenship Country, Birth Date, Birth Year, Entry Date, Entry Status, Known Terrorist Yes No, Suspected Gang Yes No, MSC Charge, MSC Charge Date, MSC Criminal Charge Status, MSC Charge Code, MSC Conviction Date, Case Criminality, Case Threat Level, Aggravated Felon Yes No, Processing Disposition, Case Category, Final Program, Final Program Code, Arresting Agency, TOA Case Category, Latest Apprehension Final Program, Latest Arresting Agency, Latest Apprehension Date, Final Order Yes No, Final Order Date, Final Charge Code, Final Charge Section, Prior Deport Yes No, Anonymized Identifier]
Index: []

[0 rows x 39 columns]

In [42]:
pdList = [dfRemovals1, dfRemovals2]
df_Removals2025 = pd.concat(pdList).drop_duplicates()
df_Removals2025

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
14,2025-09-16 08:33:41,Collateral,NEW YORK,NaN,Boston Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,BRAZIL,Male,2025-12-22 00:00:00,2025-12-04 00:00:00,FUGITIVE OPERATIONS MA,Boston,"BOSTON, MA, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,0003d477c82b5f0795916635f4da101d37d6924c
43,2025-01-28 12:26:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,SENEGAL,Male,2025-04-10 00:00:00,2023-03-03 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000c16c2e97d9a2d6a84ec0954b1fd204ee96634
52,2025-07-25 11:29:25,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-10-23 00:00:00,2025-09-26 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000e1b3e91ccc931e58311ebe59363dfb727adc9
70,2025-06-09 13:03:41,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0014a87083eb6ebdd1e1d6563016150e7aa8ae50
99,2025-09-12 14:29:15,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,ECUADOR,Male,2025-12-02 00:00:00,2019-10-28 00:00:00,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",1 Convicted Criminal,3,001c20aa9fa402e9dfe2fe2552a49ce677540953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184814,2025-10-21 08:34:15,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,EL SALVADOR,Male,NaN,NaN,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN
185156,2025-10-31 07:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
186543,2025-12-03 10:26:19,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,GUATEMALA,Male,NaN,NaN,"NBG GENERAL AREA, NON-SPECIFIC",NaN,"Newburgh NY, Sub-Office",NaN,NaN,NaN
186642,2025-12-04 17:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
189191,2025-12-28 20:40:32,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,ECUADOR,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [43]:
df_Arrests2025.to_csv('FilteredData/All2025ICEArrests.csv', index=False)